name: Deploy Netlify Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
